apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: 'docker-registry.jx.35.198.54.220.nip.io/hfrazon/{{.APP_NAME}}'
    context: ./docker/wildfly/
    docker: {}
  tagPolicy:
    envTemplate:
      template: 'docker-registry.jx.35.198.54.220.nip.io/hfrazon/{{.APP_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
##############
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: 'docker-registry.jx.35.198.54.220.nip.io/hfrazon/{{.APP_NAME}}:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: '{{.APP_NAME}}'
        chartPath: 'charts/{{.APP_NAME}}'
        setValueTemplates:
          image.repository: 'docker-registry.jx.35.198.54.220.nip.io/hfrazon/{{.APP_NAME}}'
          image.tag: '{{.DIGEST_HEX}}'
