apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: '10.15.253.13:5000/sfb-cicd/gs-serving-web-content'
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '10.15.253.13:5000/sfb-cicd/gs-serving-web-content:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
##############
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '10.15.253.13:5000/sfb-cicd/gs-serving-web-content:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: 'gs-serving-web-content'
        chartPath: 'charts/gs-serving-web-content'
        setValueTemplates:
          image.repository: '10.15.253.13:5000/sfb-cicd/gs-serving-web-content'
          image.tag: '{{.DIGEST_HEX}}'
