apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: '{{.DOCKER_REGISTRY}}/sfb-cicd/gs-serving-web-content'
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/sfb-cicd/gs-serving-web-content:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
##############
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/sfb-cicd/gs-serving-web-content:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: 'gs-serving-web-content'
        chartPath: 'charts/gs-serving-web-content'
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/sfb-cicd/gs-serving-web-content'
          image.tag: '{{.DIGEST_HEX}}'
