apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Rolling
    rollingParams:
      intervalSeconds: {{ .Values.intervalSeconds }}
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
      timeoutSeconds: {{ .Values.timeoutSeconds }}
      updatePeriodSeconds: {{ .Values.updatePeriodSeconds }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  
        resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}    
              memory: {{ .Values.resources.limits.memory }}          
        ports:
          - containerPort: 8080
            protocol: "TCP"
        livenessProbe:
          failureThreshold: 20
          httpGet:
            path: /greeting
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: greeting
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /greeting
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1                                