# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
intervalSeconds: 1
maxSurge: 25%
maxUnavailable: 0
timeoutSeconds: 900
updatePeriodSeconds: 1
image:
  repository: docker-registry.jx.35.198.54.220.nip.io/sfb-cicd/gs-serving-web-content
  tag: 0.1.10
  pullPolicy: IfNotPresent

service:
  name: gs-serving-web-content
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

nameOverride: gs-serving-web-content