# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
intervalSeconds: 1
maxSurge: 25%
maxUnavailable: 0
timeoutSeconds: 900
updatePeriodSeconds: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

service:
  name: gs-serving-web-content
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

# resources:
#   limits:
#     cpu: '2'
#     memory: '1024Mi'

nameOverride: gs-serving-web-content